export const imageList = [
    { id: 1, imgUrl: '/images/img1.jpg' },
    { id: 2, imgUrl: '/images/img2.jpg' },
    { id: 3, imgUrl: '/images/img3.jpg' },
    { id: 4, imgUrl: '/images/img4.jpg' },
    { id: 5, imgUrl: '/images/img5.jpg' },
    { id: 6, imgUrl: '/images/img6.jpg' },
    { id: 7, imgUrl: '/images/img7.jpg' },
    { id: 8, imgUrl: '/images/img8.jpg' },
    { id: 9, imgUrl: '/images/img9.jpg' },
    { id: 10, imgUrl: '/images/img10.jpg' },
    { id: 11, imgUrl: '/images/img11.jpg' },
    { id: 12, imgUrl: '/images/img12.jpg' },
    { id: 13, imgUrl: '/images/img13.jpg' },
    { id: 14, imgUrl: '/images/img14.jpg' },
    { id: 15, imgUrl: '/images/img15.jpg' },
    { id: 16, imgUrl: '/images/img16.jpg' },
    { id: 17, imgUrl: '/images/img17.jpg' },
    { id: 18, imgUrl: '/images/img18.jpg' },
    { id: 19, imgUrl: '/images/img19.jpg' },
    { id: 20, imgUrl: '/images/img20.jpg' },
    { id: 21, imgUrl: '/images/img21.jpg' },
    { id: 22, imgUrl: '/images/img22.jpg' },
    { id: 23, imgUrl: '/images/img23.jpg' },
    { id: 24, imgUrl: '/images/img24.jpg' },
    { id: 25, imgUrl: '/images/img25.jpg' },
    { id: 26, imgUrl: '/images/img26.jpg' },
    { id: 27, imgUrl: '/images/img27.jpg' },
    { id: 28, imgUrl: '/images/img28.jpg' },
    { id: 29, imgUrl: '/images/img29.jpg' },
    { id: 30, imgUrl: '/images/img30.jpg' },
    { id: 31, imgUrl: '/images/img31.jpg' },
    { id: 32, imgUrl: '/images/img32.jpg' },
    { id: 33, imgUrl: '/images/img33.jpg' },
    { id: 34, imgUrl: '/images/img34.jpg' },
    { id: 35, imgUrl: '/images/img35.jpg' },
    { id: 36, imgUrl: '/images/img36.jpg' },
    { id: 37, imgUrl: '/images/img37.jpg' },
    { id: 38, imgUrl: '/images/img38.jpg' },
    { id: 39, imgUrl: '/images/img39.jpg' },
    { id: 40, imgUrl: '/images/img40.jpg' },
    { id: 41, imgUrl: '/images/img41.jpg' },
    { id: 42, imgUrl: '/images/img42.jpg' },
    { id: 43, imgUrl: '/images/img43.jpg' },
    { id: 44, imgUrl: '/images/img44.jpg' },
    { id: 45, imgUrl: '/images/img45.jpg' },
    
    
    
]